baseurl = "https://www.openhwgroup.org/"
DefaultContentLanguage = "en"
title = "" 
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomyTerm"]
themesDir = "node_modules/"

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "OpenHW Group is a not-for-profit, global organization driven by its members and individual contributors where hardware and software designers collaborate on open source cores, related IP, tools and software projects."
  subtitle = ""
  seo_title_suffix = " | OpenHW Group"
  keywords = ["open-source", "risc-v", "hardware", "software", "hw", "sw", "eclipse ide"]
  logo = "images/openhw-landscape.svg"
  styles = "css/styles.css"
  favicon = "images/favicon.ico"
# share_img = ""
  gcse = ""
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "OpenHW Group"
  website = "https://www.openhwgroup.org"
  email = "info@openhwgroup.org"
# facebook = ""
  twitter = "openhwgroup"
# youtube = ""
# googleplus = ""
# linkedin = ""

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  
[[menu.main]]
    name = "CORE-V Family"
    url = "/#core-v-family"
    weight = 1
    
[[menu.main]]
    name = "Testimonials"
    url = "/#testimonials"
    weight = 2
    
[[menu.main]]
    name = "Membership"
    url = "/membership"
    weight = 3
    
[[menu.main]]
    name = "About Us"
    url = "/#about-us"
    weight = 3
    
[[menu.main]]
    name = "Contact Us"
    url = "/#contact-us"
    weight = 4
