baseurl = "https://www.openhwgroup.org/"
DefaultContentLanguage = "en"
title = ""
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomyTerm"]
themesDir = "node_modules/"

[Params]
  website_type = "Working Group"
  google_tag_manager = "GTM-5WLCZXC"
  layout_style = "astro"
  description = "OpenHW Foundation is an Eclipse Foundation Working Group driven by its members and individual contributors where hardware and software designers collaborate on open source cores, related IP, tools and software projects."
  subtitle = ""
  seo_title_suffix = " | OpenHW Foundation"
  keywords = ["open-source", "risc-v", "hardware", "software", "hw", "sw", "eclipse ide"]
  logo = "/images/openhw-landscape.png"
  logo_width = "200"
  styles = "css/styles.css"
  favicon = "images/favicon.ico"
# share_img = ""
  gcse = ""
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  hide_call_for_action = true
  js = "js/solstice.js"
  featured_content_publish_target = "openhwgroup"
  call_for_action_text = "Download"
  call_for_action_url = "#"
  call_for_action_icon = ""
  jumbotron_class = "col-sm-20 col-sm-offset-2"
  hide_footer_newsletter = true

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "OpenHW Group"
  website = "https://www.openhwgroup.org"
  email = "info@openhwgroup.org"
# facebook = ""
  twitter = "openhwgroup"
# youtube = ""
# googleplus = ""
# linkedin = ""

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

# About Menu

[[menu.main]]
  name = "About"
  weight = 1
  identifier = "about"

[[menu.main]]
  name = "OpenHW Foundation"
  url = "/about-us/"
  weight = 1
  parent = "about"

[[menu.main]]
  name = "CORE-V RISC-V Cores"
  url = "/about-us/core-v-risc-v-cores/"
  weight = 2
  parent = "about"

[[menu.main]]
  name = "CORE-V DevKits"
  url = "/core-v-devkits/"
  weight = 3
  parent = "about"

# Membership Menu

[[menu.main]]
  name = "Membership"
  url = "/membership/"
  weight = 2
  identifier = "membership"

[[menu.main]]
  name = "Our Members"
  url = "/membership/members/"
  weight = 1
  parent = "membership"

[[menu.main]]
  name = "Become a Member"
  url = "/membership/become-a-member/"
  weight = 2
  parent = "membership"

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "Get Involved"
  url = "/get-involved/"
  weight = 4

[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 5
  identifier = "resources"

[[menu.main]]
  name = "Events"
  url = "/events/"
  parent = "resources"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/resources/blog/"
  parent = "resources"
  weight = 2

[[menu.main]]
  name = "OpenHW TV"
  url = "/resources/openhwtv"
  parent = "resources"
  weight = 3
