baseurl = "https://www.openhwgroup.org/"
DefaultContentLanguage = "en"
title = "" 
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomyTerm"]
themesDir = "node_modules/"

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "OpenHW Group is a not-for-profit, global organization driven by its members and individual contributors where hardware and software designers collaborate on open source cores, related IP, tools and software projects."
  subtitle = ""
  seo_title_suffix = " | OpenHW Group"
  keywords = ["open-source", "risc-v", "hardware", "software", "hw", "sw", "eclipse ide"]
  logo = "images/openhw-landscape.svg"
  styles = "css/styles.css"
  favicon = "images/favicon.ico"
# share_img = ""
  gcse = ""
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
  featured_content_publish_target = "openhwgroup"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "OpenHW Group"
  website = "https://www.openhwgroup.org"
  email = "info@openhwgroup.org"
# facebook = ""
  twitter = "openhwgroup"
# youtube = ""
# googleplus = ""
# linkedin = ""

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  
[[menu.main]]
    name = "About Us"
    url = "/about-us"
    weight = 1
    
[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 2
    
[[menu.main]]
    name = "Membership"
    url = "/membership"
    weight = 3
    
[[menu.main]]
    name = "Working Groups"
    url = "/working-groups"
    weight = 4
    
[[menu.main]]
    name = "Resources"
    url = "/"
    weight = 5
    
[[menu.main]]
    name = "Contact Us"
    url = "/#contact-us"
    weight = 6

# Membership submenus
[[menu.main]]
    name = "Member Benefits and Services"
    url = "/membership#tab-benefits"
    parent = "Membership"
    weight = 1
[[menu.main]]
    name = "Membership Levels"
    url = "/membership#tab-levels"
    parent = "Membership"
    weight = 2
[[menu.main]]
    name = "Membership Fees"
    url = "/membership#tab-fees"
    parent = "Membership"
    weight = 3
[[menu.main]]
    name = "Become a Member"
    url = "/membership#tab-membership"
    parent = "Membership"
    weight = 4
[[menu.main]]
    name = "Explore our Members"
    url = "/membership/members"
    parent = "Membership"
    weight = 5

# Resources submenus
[[menu.main]]
    name = "OpenHW Mattermost"
    url = "https://mattermost.openhwgroup.org/all-users/channels/town-square"
    parent = "Resources"
    weight = 1
[[menu.main]]
    name = "OpenHW Read the Docs"
    url = "https://readthedocs.com/organizations/openhw-group/"
    parent = "Resources"
    weight = 2
[[menu.main]]
    name = "OpenHW Project Dashboard"
    url = "https://github.com/openhwgroup/core-v-docs/blob/master/program/dashboard/Dashboard.md"
    parent = "Resources"
    weight = 3
[[menu.main]]
    name = "OpenHW Project Descriptions"
    url = "https://github.com/openhwgroup/core-v-docs/tree/master/program/Project-Descriptions-and-Plans"
    parent = "Resources"
    weight = 4
[[menu.main]]
    name = "OpenHW TV"
    url = "/resources/openhwtv/"
    parent = "Resources"
    weight = 5
[[menu.main]]
    name = "Blog"
    url = "/resources/blog/"
    parent = "Resources"
    weight = 6