[build]
publish = "public"
command = "npm run build_netlify && hugo --gc --minify -b https://eclipsefdn-openhwgroup.netlify.com"

[context.production.environment]
HUGO_VERSION = "0.76.5"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run build_netlify && hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.76.5"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build_netlify && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.76.5"

[context.branch-deploy]
command = "npm run build_netlify && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.76.5"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
